name: ransacflow

channels:
  - defaults
  - conda-forge

dependencies:
  # core
  - python=3.8
  - pip
  # this pulls in ipy* packages, allow integration with jupyter
  - ipywidgets
  # development
  - black
  - flake8
  # math libs, accelerated
  - numpy
  - scipy
  # others
  - matplotlib
  - scikit-image
  - pip:
    # use pip to avoid install cudatoolkit from conda
    - kornia
    - pytorch-lightning
    - torch
    - torchvision
    #- opencv-contrib-python-headless
